### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by soneeka** [Women-Leaders-in-Technology/WLiT-internship-site-2020#12]
- [x] Two different logos used 
- [x] Carousel must be repetitive 
- [x] Navbar element if hover, it moves left side
- [x] If hover then, frame comes in left upper corner only, supposed to appear in right lower corner also
- [ ] Font(colour,size) doesn't match the design, I think
- [x] After few scrolling, when navbar is placed stable in uppermost side, navigation doesn't work

**Comment by rajinashrestha** [comment]
For home page, [https://staging.wlit.org.np/home](url) @Kanchan112 
- [ ] November 2019 Present, doesn't have a dash in between. 
- [ ] I'm not sure where you got the dates July 2019 September 2019 WLiT Fellowship 2019-2020, but it's not correct. Did we give it to you? Let me know the source so I can edit it
- [ ] Is "See more" supposed to be clickable?
- [ ] The first photo in "Gallery" is misplaced.
- [ ] LinkedIn and Medium publication to be added in social media handles

**Comment by rajinashrestha** [comment]
For about page [https://staging.wlit.org.np/about](url) @BijinaRegmi 

- [ ] Around the picture with Nishla, Not sure what the picture that isn't loading is. Also, the text block looks weird as two parts. 
- [ ] What is there an EN|NP? are we leaving space for a Nepali site??
- [ ] LinkedIn and Medium publication to be added in social media handles

**Comment by soneeka** [comment]
The most of the things in this issue has been covered and merged. So, closing this issue now.
